Update sessionizer

diff --git a/tmux/tmux-sessionizer b/tmux/tmux-sessionizer
--- a/tmux/tmux-sessionizer
+++ b/tmux/tmux-sessionizer
@@ -1,14 +1,16 @@
 #!/usr/bin/env bash
 
 ################################################################################
-#                           TMUX Sesisonizer
-#                         Updated: 2024/11/18
+#                           TMUX Sessionizer
 #
 #         The TMUX Sessionizer is a tool for creating or switching 
 #         sessions in tmux by (project / directory) names.
 #
 #
 ################################################################################
+
+
+#Find Directory
 
 
 usage="\
@@ -18,7 +20,7 @@ txs [-r][-v][-h][-p][-n {Name Arg}] {Directory Args...}
 
 Options:
  -r: Use sub directories for selection (depth = 1)
- -v: Vebose logging
+ -v: Verbose logging
  -p: Enable preview in fzf
  -h: Help
  -n: Specify the session name
@@ -38,7 +40,7 @@ Examples
 
  4.) Open a directory with as specified session name
 
-      tmux-sessionizer -n Projcet ~/My_Project
+      tmux-sessionizer -n Project ~/My_Project
 
  5.) Fuzzy Find a project folders in multiple directories
 
@@ -106,10 +108,24 @@ verbose() {
   fi
 }
 
+switch_to() {
+    if [[ -z $TMUX ]]; then
+        tmux attach-session -t $1
+    else
+        tmux switch-client -t $1
+    fi
+}
 
-# set echo >&2 to avoid pollution of function capture
-err() {
-  echo -e >&2 "${yellow}Error:${clear} $1"
+has_session() {
+    tmux list-sessions | grep -q "^$1:"
+}
+
+hydrate() {
+    if [ -f $2/.tmux-sessionizer ]; then
+        tmux send-keys -t $1 "source $2/.tmux-sessionizer" c-M
+    elif [ -f $HOME/.tmux-sessionizer ]; then
+        tmux send-keys -t $1 "source $HOME/.tmux-sessionizer" c-M
+    fi
 }
 
 open_session(){
@@ -117,27 +133,22 @@ open_session(){
   local dir=$2
   local tmux_running=$(pgrep tmux)
 
-  verbose "Openeing Session"
+  verbose "Opening Session"
   verbose "Name: $name"
   verbose "Directory: $dir"
 
   if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
-    tmux new-session -A -s "$name" -c "$dir" \
-    -e "TSX_PROJECT_DIR=\"$dir\"" -e "TSX_PROJECT_NAME=\"$name\""
+      tmux new-session -s $name -c $dir
+      hydrate $name $dir
+      exit 0
   fi
 
-  if [[ -z $TMUX ]]; then
-    tmux new-session -Ad -s "$name" -c "$dir" \
-    -e "TSX_PROJECT_DIR=\"$dir\"" -e "TSX_PROJECT_NAME=\"$name\""
+  if ! has_session $name; then
+      tmux new-session -ds $name -c $dir
+      hydrate $name $dir
   fi
 
-  if [[ -z $TMUX ]]; then
-    tmux attach -t "$name" 
-  elif [[ $name -ne "$( tmux display-message -p '#S' )" ]]; then
-    tmux switch-client -t "$name" 
-  fi 
-   
-  return 0
+  switch_to $name
 }
 
 test_directories(){
@@ -199,7 +210,7 @@ tmux_session_status(){
 
 
 select_directory(){
-  local fzf_defualt=( '--header-lines=1' 
+  local fzf_default=( '--header-lines=1' 
                       '--color=dark'  
                       '--ansi' 
                       '--delimiter' '/'
@@ -211,6 +222,7 @@ select_directory(){
   local stop_icon=$( printf "${yellow}${clear}" ) 
 
   if "$preview"; then
+    # TMUX changes all periods(.) to underscores(_)
     preview_script="\
         session_name=\"\$( echo {-1} | sed 's/\\./_/g' )\"
         tmux capture-pane -ept \$session_name 2>/dev/null
@@ -223,11 +235,11 @@ select_directory(){
   selected_dir=$(  echo -e "$fzf_header\n$*" | \
                    column -s, -t | \
                    sed s/^i/"${start_icon}"/\;s/^o/"${stop_icon}"/ |  \
-                   fzf "${fzf_defualt[@]}" "${fzf_preview[@]}" | \
+                   fzf "${fzf_default[@]}" "${fzf_preview[@]}" | \
                    awk -F '[ \t]*' '{ print $2 }' )
 
   if [[ "$selected_dir" = ""  ]];then
-    log "${red}Error${clear}: Fzf failed to retrive directory $dirs"
+    log "${red}Error${clear}: Fzf failed to retrieve directory $dirs"
     return 1
   fi
 
@@ -239,8 +251,8 @@ get_name(){
 
   if [[ "$name" = '' ]]; then 
 
-    if ! name=$( basename "$1" | tr . _ | tr : _ ); then
-      log "${red}Error${clear}: Getting baename failed, $selected_dir"
+    if ! name=$( basename "$1" | tr . _ ); then
+      log "${red}Error${clear}: Getting basename failed, $selected_dir"
       return 1
     fi 
 
@@ -259,20 +271,17 @@ if [[ $dirs = "" ]]; then
   exit 2
 fi
 
-
 verbose "Directory Count: $#"
 
 if [[ $recursive = false && $# = 1  ]]; then
 
   if ! test_directories $dirs ; then
-   err "test_directories"
    exit 1
   fi
   
   selected_dir="$dirs"
 
   if ! get_name $selected_dir; then
-    err "get_name"
     exit 1
   fi 
   
@@ -285,19 +294,16 @@ fi
 if [[ $recursive = false ]]; then
 
   if ! test_directories $dirs ; then
-   err "test_directories"
    exit 1
   fi
 
   dirs=$( tmux_session_status $dirs | sort )
 
   if ! select_directory $dirs; then
-   err "select_directory"
    exit 1
   fi
 
   if ! get_name $selected_dir; then
-    err "get_name"
     exit 1
   fi 
 
@@ -309,26 +315,20 @@ fi
 if [[ $recursive = true ]]; then
 
   if ! test_directories $dirs ; then
-   err "test_directories"
    exit 1
   fi
 
   if ! get_sub_directories $dirs; then
-    err "get_sub_directories"
     exit 1
   fi
 
   sub_dirs=$( tmux_session_status $sub_dirs | sort )
 
-  verbose "Sub-Directory Count: ${#sub_dirs[@]}"
-
   if ! select_directory "$sub_dirs"; then
-    err "select_directory"
    exit 1
   fi
 
   if ! get_name $selected_dir; then
-    err "get_name"
     exit 1
   fi 
 
@@ -338,5 +338,4 @@ if [[ $recursive = true ]]; then
 fi
 
 exit 0
-
 
